#!/usr/bin/env python

'''

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''

import time
import argparse
import fileinput
import sys

#CLI Arguments parser section
parser = argparse.ArgumentParser(usage='Pipe a textfile into this script and it will spritz-like show it to you.\n\tCtrl + C to close\n\tCtrl + Z to suspend (then fg to resume)',description='Spydreader: a command-line python-based speedreader')
parser.add_argument('--wpm', help='Sets the number of words shown per minute', default='600')
#TODO parser.add_argument('--curse', help='Sets the number of words shown per minute', default='600')
args = parser.parse_args()
wpm=vars(args)["wpm"]

#Some global constants
class constants:
    LINESIZE = 40
    VOWELS = ["a","e","i","o","u"]
class bcolors:
    BLUE = '\033[94m'
    RED = '\033[01;31m'
    ENDCOLOR = '\033[0m'

#finds the pivot (the red letter)
def splitter(word):
    toreturn = dict()
    if len(word) <=1:
        toreturn["prefix"]= ""
        toreturn["suffix"]= ""
        toreturn["pivot"] = word
        return toreturn
    else:
        found= False
        half = (len(word)) // 2 - 1 
        for i in range (half, 0,-1):
            if word[i].lower() in constants.VOWELS:
                found = True
                toreturn["prefix"]= word[0:i]
                toreturn["suffix"]= word[i + 1 : len(word)]
                toreturn["pivot"] = word[i]
        if not found:
            toreturn["prefix"]= word[0:half]
            toreturn["suffix"]= word[half + 1 : len(word)]
            toreturn["pivot"] = word[half]
    return toreturn

#Prints the data centered around the pivot
def wordprinter(data):
        towrite="\r" + " "*(constants.LINESIZE // 2 - len(data["prefix"])) + data["prefix"] + bcolors.RED + data["pivot"] + bcolors.ENDCOLOR + data["suffix"] + " "*(constants.LINESIZE // 2 - len(data["suffix"]))
        sys.stdout.write(towrite.encode('utf-8'))
        sys.stdout.flush() 


print ""  
print " "*(constants.LINESIZE //2 - 13)+u"-- Welcome to spydreader --"
print "-"*(constants.LINESIZE)
print " "*(constants.LINESIZE//2) + "|"   

#Mainloop code
for line in sys.stdin:
    line = line.decode('utf-8')
    for word in line.split():
        data=splitter(word)
        wordprinter(data)
        time.sleep(60 / float(wpm))


print ""  
print " "*(constants.LINESIZE//2) + "|"   
print "-"*(constants.LINESIZE)
print " "*(constants.LINESIZE //2 - 4)+u"-- EOF --"
print ""
